[package]
name = "topology"
version = "0.1.0"
authors = ["Jedrzej Stuczynski <andrew@nymtech.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11.0"
curve25519-dalek = "1.2.3"
itertools = "0.8.2"
log = "0.4.8"
rand = "0.7.2"
serde = { version = "1.0.104", features = ["derive"] }

## internal
addressing = {path = "../addressing"}

## will be moved to proper dependencies once released
sphinx = { git = "https://github.com/nymtech/sphinx", rev="2891b1ac203c8928504c9cd9c5784b54aee2e34d" }
